spring:  application:    name: config-server  cloud:    config:      server:        git:          uri: https://github.com/Sakethpavan/configuration          search-paths:          - "*service"
server:  port: 8888



